# version: '3'
services:
  fastbuka-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastbuka-api:1.0.0
    container_name: fastbuka-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@localhost:5432/fastbuka
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:prod"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastbuka
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
